#!/bin/bash
# get-pages-from-urllist works on newline separated list of filenames

PROGRAM=`basename "$@"`
VERSION='1.0'
CURRENT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOWNLOAD_DIR=$CURRENT_DIR/'download_'`date +%Y-%m-%d.%H.%M`
INPUTFILE="$1"

# Start by removing any \r (carriage return) occurrences

sed -i 's/\r//g' $INPUTFILE

# Make newlines (\n) the only separator

#IFS=$'\n'

# disable globbing

#set -f



while IFS='\n' read -r line;
do
  echo Now downloading $line
  wget $line -P $DOWNLOAD_DIR
done <$INPUTFILE

#for i in $(cd $DOWNLOAD_DIR ; echo *)
for i in `cd $DOWNLOAD_DIR ; ls *`
do
  echo Tidying HTML $i
  tidy -asxhtml --write-back=true $1
done 

# tidy -asxhtml bog1.html > bog1.tidy.html

#for i in $(cat < "$1"); do
#	echo "Henter: $i"
#	wget "https://sproget.dk/nyheder/$i"
#done

#while IFS="" read -r p || [ -n "$p"]
#do
#  wget "https://sproget.dk/nyheder/$p"
#done < nyheder-liste
