#!/bin/bash
#This shell script crops odd file numbers (i.e. 1,3,5,7..)

convert-image(){
  convert "$@" -crop 1800x2800+260+200 ${@/.jpg/}_crop.jpg
}

cnt=0
for f in "$@"
do
  let cnt=cnt+1
    if [ $cnt -eq 2 ]
      then convert-image "$f"
      cnt=0;
    fi
done
