#!/bin/bash
#This shell script crops odd file numbers (i.e. 1,3,5,7..)

cnt=0
for i in *.jpg; do
	let cnt=cnt+1
        if [ $cnt -eq 2 ];
        then convert $i -crop 1800x2800+260+200 ${i/.jpg/}_crop.jpg
        cnt=0;
        fi;
done
