#!/bin/bash
# ocrBatch -- a simple shell script for doing batch OCR with
# tesseract
# todo: I want to be able to provide tesseract image file 
# extensions and language parameters like deu_frak as parameters


PROGRAMNAME=`basename "$0"`                      # Program name
VERSION='1.0'
INPUTFILENAME=$(basename $1 .pdf)
CURRENT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRATCHDIR=`mktemp -d -p "$CURRENT_DIR"`

usage() {
  echo >&2 "$PROGRAMNAME" - convert a PDF file into text, v"$VERSION"
  usage: "$PROGRAMNAME" [-h] [file]
}

while getopts :hv opt
do
    case "$opt" in
                                        # your flags here
        h)      usage;;
        v)      echo "$PROGRAMNAME - convert a PDF into text, v$VERSION" >&2
                exit 1;;
     '?')    echo "$0: invalid option -$OPTARG" >&2
                echo "usage: $0 [-hv] [file ...]" >&2
           exit 1
           ;;
    esac
    shift
done

shift $((OPTIND - 1))                   #Remove options, leave arguments

split-pdf-in-pages() {

  # Use pdfseparate for splitting input file into separate pages
  # and send output into temporary directory

  pdfseparate $1 $SCRATCHDIR/'page_%04d.pdf'

}

convert-pages-to-jpg() {
  #outputfolder=$(mkdir -p $SCRATCHDIR/outputfolder)

  for i in `cd $SCRATCHDIR ; ls *`
  do
    echo Converting $i into jpeg
    convert \
      -verbose \
      -density 150 \
      -trim \
      "$SCRATCHDIR/$i" \
      -quality 100 \
      -flatten \
      -sharpen 0x1.0 \
      "$SCRATCHDIR/$(basename "$SCRATCHDIR/$i" .pdf).jpg"
  done
}

do-ocr() {

  for i in `cd $SCRATCHDIR ; ls *.jpg`
  do
    echo Doing OCR on $i
    b=`basename "$i" .jpg`
    tesseract -l dan "$SCRATCHDIR/$i" "$SCRATCHDIR/$b";
  done

}

make-textfile() {

  cat $SCRATCHDIR/*.txt > $INPUTFILENAME.txt
  
  # Reduce multiple blank lines to one

  sed -i.pre-clean-backup \
    # Remove any form feed characters
    -e 's/\f//g' \
    # Reduce multiple newlines to one
    -e '/^$/{N;/^\n$/d;}' \
    $INPUTFILENAME.txt
}



split-pdf-in-pages $1; convert-pages-to-jpg; do-ocr ; make-textfile
