#!/bin/bash

# Usage: In a directory with html-files do
# ./spellcheck-html-files
#

for f in *; do 
	printf "\n" \
	&& basename $f \
	&& printf "\n" \
	&& cat $f | aspell list -l da -H | sort -u 
done
