#!/usr/bin/env bash

# topWords is a filter that takes a number 'n' as input and presents
# the top 'n' words in a text-file. Usage: cat file.txt | topWords 10

PROGRAM=`basename"$0"`
VERSION="1.0"
NUM_WORDS="$1"

usage () {
  echo >&2 "$PROGRAM - show top frequent words in text-file, v$VERSION
  usage: cat file.txt | $PROGRAM [-h]" 
  exit 1
}

tr '[:upper:]' '[:lower:]' | grep -oE '\w+' | sort | uniq -c | sort -nr | head -n $NUM_WORDS
