#! /bin/bash
# Read a text stream on standard input, and output a list of
# the n (default: 25) most frequently occurring words, and 
# their frequency counts, in order of descending counts, on
# standard output.
#
# Usage:
# 	wf [n]
#	wf 10 < filename

tr -cs A-Za-z\' '\n' |		#replace nonletters with newlines
  tr A-Z a-z |			#map upper- to lowercase
    sort |			#sort words in ascending order
      uniq -c |			#eliminate duplicates, showing counts
        sort -k1,1nr -k2 |	#sort by descending count, then ascending word
          sed ${1:-25}q		#print only first 25 lines
