[xenophon_1600]
  name = "Goerg von Wolframsdorf"
  sortname = "Wolframsdorf, georg von"
  lifetime = "-1600-"
  description = "Tysk adelsmand. Kæmner hos Christian 2. af Sachsen."

[beta_betasson_1600]
  name = "Goerg von Wolframsdorf"
  sortname = "Wolframsdorf, georg von"
  lifetime = "-1600-"
  description = "Tysk adelsmand. Kæmner hos Christian 2. af Sachsen."

