#!/bin/bash

# process-ocr is a filter for adding XML markup to a text rendering of
# a scanned bookpage. Usage: process-ocr [-h] [files(s)] > filename

PROGRAM=`basename "$0"`                 # Program name
VERSION='1.0'				# Version name
FILES='*.html'

usage () {
    echo >&2 "$PROGRAM - batch convert HTML files to Github flavored markdown using pandoc, v$VERSION
    usage: $PROGRAM [-h] [file(s) ...]"
    exit 1
}

while getopts :hv opt
do
    case "$opt" in
                                        # Your flags here
        h)      usage;;
        v)      echo "$PROGRAM - batch convert HTML files to Github flavored markdown using pandoc, v$VERSION" >&2
                exit 1;;
        '?')    echo "$0: invalid option -$OPTARG" >&2
		echo "usage: $0 [-hv] [file(s) ...]" >&2
           exit 1
           ;;
    esac
    shift
done

shift $((OPTIND - 1))                   			# Remove options, leave arguments

for f in $FILES
do
  # extension="${f##*.}"
  filename="${f%.*}"
  echo "Converting $f to $filename.md"
  `pandoc $f -f html -t gfm -o $filename.md`
  # uncomment this line to delete the source file.
  # rm $f
done

