#!/bin/bash
# add XML to scanned book page

PROGRAM=`basename "$0"`                 # Program name
VERSION='1.0'				# version name

usage () {
    echo >&2 "$PROGRAM - add XML tags to scanned book page, v$VERSION
    usage: $PROGRAM [-h] [file(s) ...]"
    exit 1
}

while getopts :hv opt
do
    case "$opt" in
                                        # your flags here
        h)      usage;;
        v)      echo "$PROGRAM - add XML tags to scanned book page, v$VERSION" >&2
                exit 1;;
        '?')    echo "$0: invalid option -$OPTARG" >&2
		echo "usage: $0 [-hv] [file(s) ...]" >&2
           exit 1
           ;;
    esac
    shift
done

shift $((OPTIND - 1))                   #Remove options, leave arguments


insert-page-breaks(){
  sed \
    -e '1s/^\([0-9]\{1,3\}\).*$/<pb n="\1" facs=""\/>/' \
    -e '1s/^[^0-9]*\([0-9]\{1,3\}\)$/<pb n="\1" facs=""\/>/' \
  "$@"
}

add-paragraphs(){
sed ´
/^$/!{
     H
     d
     }
/^$/{
        x
        s/^\n/<p>/
        s/$/<\/p>/
        G
     }´ "$@"
}

for f in "$@"
do
  insert-page-breaks "$f"
  #add-paragraphs "$f"
done
